name: praugas_site
description: praugas.com Homepage website.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  responsive_builder: ^0.3.0
  get: ^3.22.2
  get_it: ^5.0.3
  http: ^0.12.2
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/front_img.png

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 400
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri-Regular.ttf